name: build java
on:
  workflow_dispatch:
jobs:
  push:
    name: "deverlopment:java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 8
            platforms: linux/amd64,linux/arm64
          - tag: 8j9
            platforms: linux/amd64,linux/arm64
          - tag: 11
            platforms: linux/amd64,linux/arm64
          - tag: 11j9
            platforms: linux/amd64,linux/arm64
          - tag: 13
            platforms: linux/amd64
          - tag: 16
            platforms: linux/amd64,linux/arm64
          - tag: 16j9
            platforms: linux/amd64,linux/arm64
          - tag: 17
            platforms: linux/amd64,linux/arm64
          - tag: 18
            platforms: linux/amd64,linux/arm64
          - tag: 18j9
            platforms: linux/amd64,linux/arm64
          - tag: 19
            platforms: linux/amd64,linux/arm64
          - tag: 19j9
            platforms: linux/amd64,linux/arm64
          - tag: 21
            platforms: linux/amd64,linux/arm64
          - tag: 21j9
            platforms: linux/amd64,linux/arm64
          - tag: 25
            platforms: linux/amd64,linux/arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set registry prefix (lowercase)
        id: registry
        run: echo "owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
        with:
            image: tonistiigi/binfmt:qemu-v7.0.0-28
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.registry.outputs.owner_lower }}
          # Use USER_TOKEN (PAT with write:packages) for org push; fallback to GITHUB_TOKEN
          password: ${{ secrets.USER_TOKEN != '' && secrets.USER_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./java
          file: ./java/${{ matrix.tag }}/Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ steps.registry.outputs.owner_lower }}/deverlopment:java_${{ matrix.tag }}

